# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/115-bFEr67lTQ_7dc90ZWV7XJ-GeR0GPR
"""

def game_core_v3(number):
    count = 1
    low = 1
    high = 101
    predict = (low + high)//2
    while number != predict:
        count +=1
        if number > predict:
            low = predict
            predict = (low + high)//2
        else:
            high = predict
            predict = (low + high)//2
    return (count)
        
def score_game(game_core):
    '''Запускаем игру 1000 раз, чтобы узнать, как быстро игра угадывает число'''
    count_ls = []
    np.random.seed(1)  # фиксируем RANDOM SEED, чтобы ваш эксперимент был воспроизводим!
    random_array = np.random.randint(1,101, size=(1000))
    for number in random_array:
        count_ls.append(game_core(number))
    score = int(np.mean(count_ls))
    print(f"Ваш алгоритм угадывает число в среднем за {score} попыток")
    return(score)

score_game(game_core_v3)